recipe: default.v1
language: en
pipeline:
- name: CompactLLMCommandGenerator
  # prompt_template: data/prompts/command-generator.jinja2
  llm:
    model_group: azure_llm
  flow_retrieval:
    # active: false
    embeddings:
        model_group: azure_embedding_model

policies:
- name: FlowPolicy

- name: EnterpriseSearchPolicy
  llm:
    model_group: azure_llm_35
  embeddings:
    model_group: azure_embedding_model



assistant_id: 20250323-071528-warm-cue
